### ISSUE TITLE
빌드하고 실행하면 앱 죽음.

### ISSUE THREAD

**Issue by BenjaminKim** [jungilhan/awesome-blogs-android#1]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.petabytes.awesomeblogs.debug, PID: 3262
                  java.lang.IllegalArgumentException: Unknown pattern character 'X'
                      at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
                      at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
                      at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
                      at org.petabytes.awesomeblogs.feeds.EntryGradientCoordinator.attach(EntryGradientCoordinator.java:49)
                      at com.squareup.coordinators.Binding.onViewAttachedToWindow(Binding.java:38)
                      at com.squareup.coordinators.Coordinators.bind(Coordinators.java:43)
                      at org.petabytes.awesomeblogs.feeds.FeedsCoordinator$1.create(FeedsCoordinator.java:72)
                      at org.petabytes.awesomeblogs.feeds.FeedsCoordinator$1.create(FeedsCoordinator.java:66)
                      at org.petabytes.coordinator.PagerAdapter.instantiateItem(PagerAdapter.java:27)
                      at fr.castorflex.android.verticalviewpager.VerticalViewPager.addNewItem(VerticalViewPager.java:729)
                      at fr.castorflex.android.verticalviewpager.VerticalViewPager.populate(VerticalViewPager.java:879)
                      at fr.castorflex.android.verticalviewpager.VerticalViewPager.populate(VerticalViewPager.java:811)
                      at fr.castorflex.android.verticalviewpager.VerticalViewPager.onMeasure(VerticalViewPager.java:1334)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                      at android.view.View.measure(View.java:18788)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteI
I/Process: Sending signal. PID: 3262 SIG: 9
Application terminated.
```

**Comment by jungilhan** [comment]
안드로이드의 SimpleDateFormat은 XXX를 지원하지 않아서 발생하는 문제, 안드로이드 SimpleDateFormat 문서에는 XXX가 있는데 ~장난 나랑 지금 하냐~, 아무튼 ```+01:00```과 같은 타임존 정보는 XXX가 아닌 ZZZZ를 사용하도록 수정해야 됨.
 * http://stackoverflow.com/questions/28373610/android-parse-string-to-date-unknown-pattern-character-x
