### ISSUE TITLE
Summary 뷰 구현하기

### ISSUE THREAD

**Issue by jungilhan** [jungilhan/awesome-blogs-android#2]

**Comment by BenjaminKim** [comment]
클릭해서 summary 뷰로 진입할때 크래시 나는 문제가 있어요.
에뮬레이터나 실제 단말기(Nexus 7 태블릿) 에서 항상 재현됨.
```
I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
W/cr_media: Requires BLUETOOTH permission
I/cr_Ime: ImeThread is enabled.
I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 6236
E/chromium: [ERROR:interface_registry.cc(99)] Failed to locate a binder for interface: autofill::mojom::AutofillDriver
E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

                     --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-10
                  Process: org.petabytes.awesomeblogs.debug, PID: 6236
                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.StackOverflowError: stack size 1038KB
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                      at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
                      at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
                      at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
                      at java.io.PrintWriter.write(PrintWriter.java:579)
                      at java.io.PrintWriter.write(PrintWriter.java:641)
                      at java.io.PrintWriter.print(PrintWriter.java:453)
                      at java.io.PrintWriter.println(PrintWriter.java:472)
                  	at com.overzealous.remark.util.BlockWri
D/Error: ERR: exClass=java.lang.StackOverflowError
D/Error: ERR: exMsg=stack size 1038KB
D/Error: ERR: file=PrintWriter.java
D/Error: ERR: class=java.io.PrintWriter
D/Error: ERR: method=write line=579
D/Error: ERR: stack=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
             at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
             at java.lang.Thread.run(Thread.java:818)
          Caused by: java.lang.StackOverflowError: stack size 1038KB
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
             at com.overzealous.remark.util.BlockWriter.testNewBlock(BlockWriter.java:227)
             at com.overzealous.remark.util.BlockWriter.write(BlockWriter.java:110)
             at java.io.PrintWriter.write(PrintWriter.java:579)
             at java.io.PrintWriter.write(PrintWriter.java:641)
             at java.io.PrintWriter.print(PrintWriter.java:453)
             at java.io.PrintWriter.println(PrintWriter.java:472)
             at com.overzealous.remark.util.BlockWriter.println(BlockWriter.java:184)
         	at com.overzealous.remark.util.BlockWriter.testNew
D/Error: ERR: TOTAL BYTES WRITTEN: 3172384
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3172468)
E/AndroidRuntime: Error reporting crash
                  android.os.TransactionTooLargeException: data parcel size 3172468 bytes
                      at android.os.BinderProxy.transactNative(Native Method)
                      at android.os.BinderProxy.transact(Binder.java:503)
                      at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4427)
                      at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                      at rx.internal.schedulers.ScheduledAction.signalError(ScheduledAction.java:68)
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
I/Process: Sending signal. PID: 6236 SIG: 9
Application terminated.
```

**Comment by jungilhan** [comment]
재현되는 단말이 필요한데, 일단은 지켜보는 걸로...

**Comment by BenjaminKim** [comment]
넵.

**Comment by jungilhan** [comment]
@BenjaminKim이 올려준 Stackoverflow 현상은 안드로이드가 PrintWriter.java코드를 독자적으로 사용하면서 발생하는 현상입니다. (https://android.googlesource.com/platform/libcore/+log/android-6.0.1_r74/luni/src/main/java/java/io/PrintWriter.java)

정리하면 Remark 라이브러리는 JDK의 PrintWriter에서 정상 동작하게 구현이 되어있는 반면 안드로이드의 PrintWriter 코드가 독자적으로 구현되어 있어 재귀적으로 함수를 호출하다가 무한루프에 빠지는 현상입니다. 안드로이드 7.0부터 PrintWriter.java를 JDK에서 클론해서 사용하기 때문에 7.0에서는 Summary view가 정상 동작한 것 입니다.
